[program:adtof-gui]
command=/var/opt/adtof-gui/.venv/bin/python /var/opt/adtof-gui/main.py
directory=/var/opt/adtof-gui
autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=10
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/opt/adtof-gui/logs/adtof-gui.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PYTHONUNBUFFERED="1",PORT="8888",ALLOWED_HOST="adtof.hubfreelas.com"
